name: 'nexus'
version: '1.0.0'
config-version: 2

profile: 'default'

vars:
  surrogate_key_treat_nulls_as_empty_strings: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nexus:
    staging:
      +materialized: view
    marts:
      +materialized: table
